### PR TITLE
change !is.null to !isFALSE, and some indents i guess...

### PR DESCRIPTION
**Pull request by pete-hulson**

### CODE REVIEW

**Comment by BenWilliams-NOAA** [comment]
But these are values that get entered (eg 120 or 80), no?

**Comment by pete-hulson** [comment]
these are the switches that say whether you want to subsample, then the param in the function is the number. one of those redundancies tho that would prolly be better to just take out the switch and if you want to subsample you put something in other than NULL. we have those (along with all the arguments to save different stuff) scattered thoughout, could do a clean up at some point

**Comment by BenWilliams-NOAA** [comment]
Yeah we need to pull those redundancies out. Shouldn’t be a switch and value, just a value will do.  Value = NULL to start then it is a question of using numbers or proportions for reduction- or could make it both eg if value < 1 use proportions

**Comment by pete-hulson** [comment]
kewl, i'll take some time this morning to try and clean things up, gonna move some of those special case fcns over into the dev folder too and have the swo package focused on the 'main' stocks. btw, i stumbled upon this yesterday - i don't think the subsample code of moving sexed to unsexed works for any of the ones that have the juvenile expansion. seems to work fine for those that don't tho. a way to see this is to compare between subsampling sex cases and subsampling total cases, while the total would include some unsexed being sampled, the results should be fairly similar and consistent, which it is for the majority of stocks except for the ones with the juvenile expansion (has to do with how the unsexed samples are used in the length comp expansion). however, the results when subsampling the total look to be reasonable, so, where i'm at now is to keep the swo tech memo as it is, since those were the results we used to make the decisions that we did, and that should be documented. but, for the journal version i'm gonna switch over to using the total subsampling since the general sex-specific results will still hold. at any rate, trying to write this down somewhere while i'm thinking about it. ultimately we need to get that juvenile expansion code to actually do this 'properly' for those species that have it for the sex sample size reduction, albeit, the total reduction should still be similar. rambling, but hopefully there's something coherent in there. oh, and we can close this pull request, i'll put in another one hopefully sometime today

**Pull request closed without merging**
